development: &global
  adapter: postgresql
  encoding: unicode
  database: cedar_development
  pool: 5
  min_messages: warning

test: &test
  database: cedar_test<%= ENV['TEST_ENV_NUMBER'] %>
  <<: *global

